### ISSUE TITLE
d4tools create randomly fails

### ISSUE THREAD

**Issue by af8** [38/d4-format#17]
When I try the command `d4tools create -Az -t2 -q10 HG00512.bam`, I got the following error message but not all the time. Sometimes it completes properly. 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(30.6502ms)', d4utils/src/create/main.rs:199:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

HG00512.bam is a small (358K) bam file with reads only on chr4 and chr8 used for testing purposes.

d4 (commit 51fa106) has been built in debian-10.5 docker image with rustup toolchain manager version 1.23.1,
cargo and rustc version 1.49.0.

Thanks
Anthony

**Comment by 38** [comment]
Thanks for reporting this. I believe this can be fix quite easily - it panics only when logging the time elapsed.
