### ISSUE TITLE
README.md refers to nonexistent d4tools crate

### ISSUE THREAD

**Issue by jmarshall** [38/d4-format#32]
Since #10 and d9a7978488ef67b15ed9335678b104f0bc647420 the previous `d4utils` command has been renamed to `d4tools`. However the README still refers to the previous command name throughout:

> **Create a D4 file**
>
> The `d4utils create` subcommand is used to convert BAM,CRAM,BigWig and BedGraph file to D4 file.
> […]
>
> * From CRAM/BAM file
>
>       d4utils create -Azr hg19.fa.gz.fai hg002.cram hg002.d4

etc

**Comment by arq5x** [comment]
Thanks for reporting this, @jmarshall. @38, PR 33(https://github.com/38/d4-format/pull/33) fixes this. However, a crate does not exist for d4tools (it is for d4utils), so the README in the PR incorrectly refers to `cargo install d4tools`. Could you please update the crate to the correct `d4toools`?

**Comment by jmarshall** [comment]
PR #33 has now been merged, fixing the original issue. The README now refers to `cargo install d4tools` but that crate does not yet appear to exist, so I'll change the issue title accordingly:

```
$ cargo search d4tools
$ cargo search d4utils
d4utils = "0.2.18"    # The CLI utils for D4 file format
d4 = "0.2.18"         # The D4 file format implementation
```

**Comment by arq5x** [comment]
Thanks @jmarshall. I know @38 has plans to update the crate as well.
