### ISSUE TITLE
Expired SSL certificate causes d4-hts installation to fail

### ISSUE THREAD

**Issue by ramprasadn** [38/d4-format#37]
Hi @38 

I am working on creating a bioconda package for d4utils and I ran into this
![Screenshot 2021-12-01 at 17 05 04](https://user-images.githubusercontent.com/20065894/144270032-9e068034-dfeb-4a12-a8e4-5ede79456467.png)

It looks like the SSL certificate for [this site from where the script downloads bzip2](https://whatsmychaincert.com/?pilotfiber.dl.sourceforge.net) has expired. Would it be possible to switch it for some other website in the next release? Perhaps [this](https://sourceware.org/pub/bzip2/bzip2-1.0.6.tar.gz)? 

Thanks!

**Comment by 38** [comment]
Of course, seems source forge doesn't maintains their certificate for some reason.

Thanks for reporting this!

**Comment by ramprasadn** [comment]
Awesome! Thanks 👍🏻

**Comment by 38** [comment]
Just let you know the change was just released
