### ISSUE TITLE
cargo build. => feature `edition2021` is required

### ISSUE THREAD

**Issue by lindenb** [38/d4-format#38]
I'm trying to play with d4.

I started with compiling the library:

```
cargo build
```

output is

```
error: failed to load manifest for workspace member `/home/lindenb/src/d4-format/d4-framefile`

Caused by:
  failed to parse manifest at `/home/lindenb/src/d4-format/d4-framefile/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

my version of cargo (installed via `apt  install cargo`) is 

```
$ cargo --version
cargo 1.53.0
```

is there something wrong or is there a minimal version of cargo required for compiling the library ?

Thanks.

**Comment by 38** [comment]
Hi there, it seems you need to use a newer Rust toolchain, as we previously changed the requirement of Rust edition from 2018 to 2021 since v0.3.0. 

Please run 
```
rustup upgrade
```
and try to compile again
