### ISSUE TITLE
Bug in build_htslib.sh?

### ISSUE THREAD

**Issue by boboppie** [38/d4-format#41]
Dear @38 ,

Thank you for developing d4tools. When I compile the latest version (0.3.2), I constantly got a missing header error (bzlib.h), then I looked into build_htslib.sh, if we change "-Ibzip2-1.0.6" at line 53 to "-Ibzip2-1.0.8", it will sort it.

Best wishes,
Fengyuan

**Comment by 38** [comment]
Hi Fengyuan,

Thanks for reporting this. I just fixed this bug in master. 

It would be nice if you can confirm the bug is actually fixed.

Thanks!

**Comment by boboppie** [comment]
Dear @38 ,

I checked out master branch to a new location, and ran the build, I can confirm it finished successfully,

Many thanks for the quick fix.

Best wishes,
Fengyuan
