### ISSUE TITLE
stat breaks pipes

### ISSUE THREAD

**Issue by snystrom** [38/d4-format#7]
Piping the output from `stat` will break pipes if printing several lines. I believe this is because `println!` is unbuffered. I think the fix is to `io::stdout` instead of `println!` as this should properly buffer the output. Below is an example using `-s hist` on 1 bed region, but the error can be caused using a bed file with multiple regions and a single-value summary stat like "mean". I believe any function that uses `println!` will have this issue.

## Example:
`d4utils stat test.d4 -r region.bed -s hist | head`

## Error:
`thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:895:9`

## System Info
This is on Ubuntu 18.04 under WSL using D4 0.1.0.

**Comment by 38** [comment]
Got this fixed in master branch, thanks for reporting the issue!

**Comment by snystrom** [comment]
Thanks! Ah, I see I was wrong about the buffering. Still a Rust newbie. 👍
